# K-nearest neighbours

## Import dataset

In [90]:
import pandas as pd
import numpy as np

dataset = pd.read_csv('/home/vutaliy/Downloads/dataset_54_vehicle.csv')
dataset.describe()

COMPACTNESS  CIRCULARITY  DISTANCE_CIRCULARITY  RADIUS_RATIO  \
count   846.000000   846.000000            846.000000    846.000000   
mean     93.678487    44.861702             82.088652    168.940898   
std       8.234474     6.169866             15.771533     33.472183   
min      73.000000    33.000000             40.000000    104.000000   
25%      87.000000    40.000000             70.000000    141.000000   
50%      93.000000    44.000000             80.000000    167.000000   
75%     100.000000    49.000000             98.000000    195.000000   
max     119.000000    59.000000            112.000000    333.000000   

       PR.AXIS_ASPECT_RATIO  MAX.LENGTH_ASPECT_RATIO  SCATTER_RATIO  \
count            846.000000               846.000000     846.000000   
mean              61.693853                 8.567376     168.839243   
std                7.888251                 4.601217      33.244978   
min               47.000000                 2.000000     112.000000   
25%               57.000000                 7.000000     146.250000   
50%               61.000000                 8.000000     157.000000   
75%               65.000000                10.000000     198.000000   
max              138.000000                55.000000     265.000000   

       ELONGATEDNESS  PR.AXIS_RECTANGULARITY  MAX.LENGTH_RECTANGULARITY  \
count     846.000000              846.000000                 846.000000   
mean       40.933806               20.582742                 147.998818   
std         7.811560                2.592138                  14.515652   
min        26.000000               17.000000                 118.000000   
25%        33.000000               19.000000                 137.000000   
50%        43.000000               20.000000                 146.000000   
75%        46.000000               23.000000                 159.000000   
max        61.000000               29.000000                 188.000000   

       SCALED_VARIANCE_MAJOR  SCALED_VARIANCE_MINOR  \
count             846.000000             846.000000   
mean              188.625296             439.911348   
std                31.394837             176.692614   
min               130.000000             184.000000   
25%               167.000000             318.250000   
50%               178.500000             364.000000   
75%               217.000000             587.000000   
max               320.000000            1018.000000   

       SCALED_RADIUS_OF_GYRATION  SKEWNESS_ABOUT_MAJOR  SKEWNESS_ABOUT_MINOR  \
count                  846.00000            846.000000            846.000000   
mean                   174.70331             72.462175              6.377069   
std                     32.54649              7.486974              4.918353   
min                    109.00000             59.000000              0.000000   
25%                    149.00000             67.000000              2.000000   
50%                    173.00000             71.500000              6.000000   
75%                    198.00000             75.000000              9.000000   
max                    268.00000            135.000000             22.000000   

       KURTOSIS_ABOUT_MAJOR  KURTOSIS_ABOUT_MINOR  HOLLOWS_RATIO  
count            846.000000            846.000000     846.000000  
mean              12.599291            188.932624     195.632388  
std                8.931240              6.163949       7.438797  
min                0.000000            176.000000     181.000000  
25%                5.000000            184.000000     190.250000  
50%               11.000000            188.000000     197.000000  
75%               19.000000            193.000000     201.000000  
max               41.000000            206.000000     211.000000

## One-Hot encoding

In [89]:
default_objects = dataset.to_numpy()

main_attribute = pd.unique(dataset['Class']) # get main attribute values
objects_amount, attributes_amount = dataset.shape # get objects and attributes amounts

zeros = np.zeros(objects_amount) # create zeros matrix with main_attribute size 
for i in range(len(main_attribute)-1):
    zeros = np.c_[zeros, np.zeros(objects_amount)]

objects = dataset.iloc[:, :attributes_amount-1].to_numpy() # slice before main attribute and convert to numpy
objects = np.c_[objects, zeros] # create matrix with new attributes
main_attribute = { main_attribute[i] : i for i in range(len(main_attribute) ) } # define main_attribute as dict

for i in range(objects_amount): # convert main attribute to several attributes
    objects[i][attributes_amount - 1 + main_attribute[default_objects[i][attributes_amount - 1]]] = 1 

print(default_objects)
print(objects)

[[95 48 83 ... 187 197 'van']
 [91 41 84 ... 189 199 'van']
 [104 50 106 ... 188 196 'saab']
 ...
 [106 54 101 ... 187 201 'saab']
 [86 36 78 ... 190 195 'saab']
 [85 36 66 ... 186 190 'van']]
[[ 95.  48.  83. ...   0.   0.   0.]
 [ 91.  41.  84. ...   0.   0.   0.]
 [104.  50. 106. ...   1.   0.   0.]
 ...
 [106.  54. 101. ...   1.   0.   0.]
 [ 86.  36.  78. ...   1.   0.   0.]
 [ 85.  36.  66. ...   0.   0.   0.]]


## Normalization and vectorization

In [ ]:
 hash_sum()

## Metrics and Kernel functions

In [131]:
from math import sqrt 

def euclidian_distance(vec1, vec2):
    ans = 0
    for i in range(len(vec1)):
        ans += (vec1[i] - vec2[i]) ** 2
    return sqrt(ans)

def manhattan_distance(vec1, vec2):
    ans = 0
    for i in range(len(vec1)):
        ans += abs(vec1[i] - vec2[i])
    return ans

def chebishev_distance(vec1, vec2):
    ans = float("-inf")
    for i in range(len(vec1)):
        ans = max(ans, abs(vec1[i] - vec2[i]))
    return ans

kernel_functions = {
    "uniform":      lambda u: 0.5,
    "triangular":   lambda u: 1 - abs(u),
    "epanechnikov": lambda u: 0.75 * (1 - u ** 2),
    "quartic":      lambda u: (15 / 16) * (1 - u ** 2) ** 2
    }

distance_functions = {
    "euclidian": euclidian_distance,
    "manhattan": manhattan_distance,
    "chebishev": chebishev_distance
}

print(euclidian_distance([0,0,1],[0,1,0]))
print(manhattan_distance([0,0,1],[0,1,0]))
print(chebishev_distance([0,0,1],[0,1,0]))

1.4142135623730951
2
1


## k-stat

In [108]:
import random

def k_stat(arr, k):
    def swap(a, b):
        t = a 
        a = b 
        b = t 


    l = 0
    r = len(arr)-1

    def partition():
        random = random.randint(l,r)
        swap(arr[r], arr[random])
        x = arr[r]
        i = l
        return 0
    
    m = partition()

    return m

k_stat([0,2,5,1,3,4,12,33], 3)


7

## Nadaraya-Watson

In [138]:
def kernel_regression(objects, x, neighbours = 0, window_size = 0, distance_function_name = "euclidian", kernel_function_name = "triangular"):
    distance_function = distance_functions[distance_function_name]
    kernel_function = kernel_functions[kernel_function_name]

    distances = [distance_function(x[:len(x)-4], obj[:len(x)-4]) for obj in objects]

    window_parameter = 0
    if (neighbours == 0):
        window_parameter = window_size 
    else:
        window_parameter = k_stat(distances, neighbours)

    sum = [0] * len(main_attribute)
    sum = np.array(sum)
    for obj in range(len(objects)):
        sum += objects[i][len(obj)-4:] * kernel_function(distances[i] / window_parameter)
    
    denominator = 0
    for dist in distance_functions: 
        denominator += kernel_function(distances[i] / window_parameter)

    return sum / denominator

kernel_regression([[1,1,1,1,1,1],[2,2,2,2,2,2],[3,3,3,3,3,3],[4,4,4,4,4,4],[5,5,5,5,5,5]], [2,2,2,2,2,2], window_size = 2)    

[1.4142135623730951,
 0.0,
 1.4142135623730951,
 2.8284271247461903,
 4.242640687119285]